const menu = [
  {
    name: "Fingerfood Buffet",
    terms:
      "Bestellmenge: mindestens 50 Teile pro Bestellung mindestens 10 Teile pro Sorte",
    buffets: [
      {
        name: "Kaltes Buffet",
        items: [
          "Schwäbische Laugenstange verschieden belegt",
          "Bagles mit Kräuterfrischkäse und Tomate",
          "Fladenbrotecke vegetarisch oder mit Fleisch gefüllt",
          "Schwäbische Laugenbrezel mit Butter oder Frischkäse",
          "Halbes Laugencroissant mit Graved Lachs",
          "Körnerbrot mit Kräuterquark und Radieschen",
          "Kräftiges Bauernbrot mit Schweinemett und Zwiebeln",
          "Blätterteigstangen mit Tomate und Käse",
          "Gemüsesticks mit Kräuterdip (40g pro Port.)",
          "Käsespieße mit Früchten (2 Stück)",
          "Melone-Schinkenspieße (2 Stück)",
          "Cabanossi und Chorizo-Spieße (2 Stück)",
          "Pilze in Balsamico Spieße (2 Stück)",
          "Tomaten-Mozzarellaspieße (2 Stück)",
          "Paprikaschiffchen mit Frischkäsefüllung",
          "Lachstatar auf gerösteter Weißbrotscheibe",
          "American Wrap (tex-mex-Füllung, Asia-Füllung, Hirtenkäse-Rucola-Füllung) mind. 8 St. pro Füllung",
          "Törtchen mit Ziegenfrischkäse und luftgetrocknetem Schinken",
          "Italienische Bruschette mit nativem Olivenöl und Tomaten",
          "Zucchiniröllchen mit Hirtenkäse und Rauke",
          "Zucchiniröllchen mit Feige und Ziegenfrischkäse",
          "Schinkenhörnchen",
          "Salat von Eismeergarnelen (im Glas serviert)¹",
          "Geflügelsalat „Bombay“ (im Glas angerichtet)¹",
          "Blätterteighalbmonde gefüllt mit scharfem Hackfleisch",
          "Blätterteighalbmonde gefüllt mit Spinat-Hirtenkäse",
          "Pumpernickel mit Schinken-Walnusscreme",
          "Blätterteigzwirbel mit Schinken, Käse u. Röstzwiebeln",
          "¹mit kleinem Besteck nicht im Lieferumfang enthalten",
        ],
      },
      {
        name: "Warmes Buffet",
        items: [
          "Nürnbergerle im Schlafrock",
          "Hackfleischtorte (2 Stück)",
          "Mediterrane Gemüsetorte (2 Stück)",
          "Quiche Lorraine (2 Stück)",
          "Tarte mit Spinat und Lachs (2 Stück)",
          "Hackfleischspieß mit verschiedenen Dips(60g)",
          "Garnelenspieße mit Knoblauchbrot (50g)",
          "Glacierte Hähnchenunterkeule asiatisch",
          "Minipizza",
          "Florentinische Käsetörtchen",
          "Yufkaröllchen gefüllt mit scharfem Hackfleisch",
          "Yufkaröllchen gefüllt mit Spinat-Hirtenkäse",
          "Yufkaröllchen gefüllt mit Frischkäse und Paprika",
          "Hähnchenspieß im Kokosmantel mit Currydip (60g)",
          "Hähnchenspieß in der Mandelpanade mit Chutney",
          "Fleischspieß in würziger Sauce (80 g)",
          "Mini-Frühlingsrollen „sweet chilli“ (4 Stück)",
          "Schinkenpäckchen „Maoui“ süß-scharf",
          "Minihaxen vom Schwein (120 g)",
        ],
      },
    ],
  },
  {
    name: "Suppen Buffet",
    terms: "Für den Suppen- und Eintopfliebhaber 0,25 l pro Portion",
    buffets: [
      {
        name: "Suppen",
        items: [
          "Kürbiscremesuppe mit Kokosmilch (saisonal)",
          "Kartoffelsuppe mit Shrimps",
          "oder mit Würstchen",
          "Tomatenrahmsuppe",
          "Schwäbische Festtagssuppe",
          "Feurige Gulaschsuppe mit Brot",
          "Gaisburger Marsch",
          "Käsesuppe mit Lauchstreifen",
          "Schwäbische Wurstknöpfle in der Brühe",
          "Deftiger Erbseneintopf",
          "Linsen Suppe ",
          "Cremige Champignons Suppe ",
        ],
      },
    ],
  },
  {
    name: "Schlemmerplatten",
    terms: "ab 10 Personen pro Person haben wir 100 Gramm kalkuliert",
    flags: ["description"],
    items: [
      {
        name: "Hirtenplatte",
        description:
          "Rustikale Auswahl von rohen Schinken, Pfefferbeißern, Landjäger, Minicabanossi und deftigen Käsespezialitäten, Essiggemüse, Bauernbrot",
      },
      {
        name: "Fischplatte",
        description:
          "Variation von Räucherlachs und Graved Lachs, geräuchertes Forellenfilet, Cocktail von Grönlandgarnelen, Lachstatarbällchen, Stangenweißbrot",
      },
      {
        name: "Käseplatte",
        description:
          "Käseplatte Internationale Käsespezialitäten, reich garniert mit Früchten und Salzgebäck, Brotauswahl",
      },
      {
        name: "Gourmetplatte Constantin",
        suffix: " (220 gr.) (ab 15 Personen)",
        description:
          "Zarter Räucherlachs mit Sahnemeerrettich, Crevettencocktail, delikate Entenbrust, Filetmedaillons bunt garniert, rosa gebratenes Roastbeef Sauce Remoulade, luftgetrockneter Schinken, französischer Camembert mit Früchten Bunter Brotkorb",
      },
    ],
  },
  {
    name: "Grill Buffet",
    terms: "ab 20 Personen",
    price: "34,50",
    buffets: [
      {
        name: "Vorspeise Und Salate",
        items: [
          "Schwäbischer Kartoffelsalat",
          "Mediterraner Nudelsalat",
          "Salat „Tabouléh“",
          "Toskanischer Brotsalat",
          "Strauchtomaten mit Mozzarella und frischem Basilikum",
          "Bunter Gemüsesalat",
          "Gurkensalat in Joghurt-Dilldressing",
          "Fenchel-Chinakohlsalat mit Orangenspalten",
          "Paprika-Maissalat",
          "Bunte Blattsalate",
          "Zwei Dressings",
          "Großer Brotkorb",
        ],
      },
      {
        name: "Hauptspeise",
        items: [
          "Auswahl von verschiedenen Würstchen",
          "Eingelegte Schweinenackensteaks",
          "Marinierte Hähnchenbrustfilets „sweet chilli“",
          "Frische Sepia in Kräuter-Olivenöl",
          "Halloumi-Grillkäse",
          "Mediterrane Gemüse aus der Pfanne",
          "Gegrillte Maiskolben",
          "Senf, Ketchup, Kräuterbutter, verschiedene Dip",
        ],
      },
      {
        name: "Nachspeise",
        items: [
          "Melonensalat",
          "Pfannkuchen mit Marmelade, Nutella oder Apfelmus gefüllt",
        ],
      },
    ],
  },
  {
    name: "Deftiges Buffet",
    terms: "ab 20 Personen",
    price: "34,80",
    buffets: [
      {
        name: "Vorspeise und Salate",
        items: [
          "Geräucherte Forellen- und Makrelenfilets",
          "Sahnemeerrettich",
          "Harzer Roller mit Essig, Öl und Zwiebeln",
          "Deftiges aus der Räucherkammer",
          "Schwäbischer Kartoffelsalat",
          "Verschiedene Rohkost- und Blattsalate zwei Dressings",
          "Bunte Brotauswahl",
        ],
      },
      {
        name: "Hauptspeise",
        items: [
          "Schinkenkrustenbraten",
          "Zartes Rinderschmorsteak „Esterhazy“",
          "Kräftige Rotweinsauce",
          "Kartoffelknödel",
          "Hausgemachte Spätzle",
          "Kartoffel-Gemüseauflauf (vegetarisch)",
          "Rustikales Gemüse",
        ],
      },
      {
        name: "Nachspeise",
        items: [
          "Kaiserschmarrn mit Apfelkompott",
          "Sahnequark mit Hägemark und frischen Früchten",
        ],
      },
    ],
  },
  {
    name: "Salatjungfer Buffet",
    terms: "ab 20 Personen",
    price: "34,80",
    buffets: [
      {
        name: "Vorspeise und Salate",
        items: [
          "Zucchiniröllchen mit Frischkäse und Feigen gefüllt",
          "Marinierter Ziegenkäse",
          "Yufka-röllchen mit Spinat- Hirtenkäsefüllung",
          "Asiatischer Gemüsesalat mit Erdnussdressing",
          "Fenchel-Chinakohlsalat mit Orangenspalten",
          "Ananas-Apfel-Karottensalat",
          "Griechischer Bauernsalat",
          "Rucola-Radicciosalat mit Walnüssen und Sherrydressing",
          "Paprika-Maissalat",
          "Gurkensalat in Joghurt-Dill Dressing",
          "Schwäbischer Kartoffelsalat",
          "Gartenfrische Blattsalate",
          "Verschiedene Dressings",
          "Selbstgebackenes Brot",
        ],
      },
      {
        name: "Hauptspeise",
        items: [
          "Paprika gefüllt mit Gemüse-Couscous",
          "Brokkoli-Nussecke und Quinoa-Erbsenbratling",
          "Kartoffel-Zucchinirösti mit Paprika",
          "Gemüsemaultaschen auf Blattspinat",
          "Tomaten-Basilikum-Concassée",
          "Helle Käse-Kräutersauce",
        ],
      },
      {
        name: "Nachspeise",
        items: [
          "Frischer Obstsalat",
          "Johannisbeer-Joghurtcreme",
          "Kirschenmichel mit Vanillesauce",
        ],
      },
    ],
  },
  {
    name: "Mediterranes Buffet",
    terms: "ab 20 Personen",
    price: "41,30",
    buffets: [
      {
        name: "Vorspeise und Salate",
        items: [
          "Gegrillte Gemüse eingelegt in nativem Olivenöl",
          "Zucchiniröllchen mit Hirtenkäse-Raukefüllung",
          "Gebratene Pilze in Balsamicodressing",
          "Verschiedene Oliven",
          "Vitello tonnato",
          "Honigmelone mit luftgetrocknetem Schinken",
          "Tomate „Caprese“",
          "Rucola mit frischen Kirschtomaten",
          "Salat „Tabouleh“",
          "Bunte Salatschüssel, zwei Dressings",
          "Selbstgebackenes Brot",
        ],
      },
      {
        name: "Frisch vom Grill und aus der Pfanne",
        items: [
          "Saltim bocca von der Pute",
          "Kleine Steaks aus der Rinderhüfte",
          "Lammbeinscheiben",
          "Kräftige Rotweinsauce",
          "Madeirasauce",
          "Bunte Tagliatelle",
          "Rosmarinkartoffeln",
          "Gefüllte Auberginen und Zucchini",
          "auf Tomatenconcassée",
        ],
      },
      {
        name: "Nachspeise",
        items: [
          "Obstplatte der Saison",
          "Mascarpone-Quarkcreme mit marinierten Kirschen",
          "Sizilianischer Cassata-Kuchen",
        ],
      },
    ],
  },
  {
    name: "Zum Kombinieren (mit Buffets oder einfach)",
    terms: "Mindestbestellmenge: 10 Portionen",
    buffets: [
      {
        name: "Hauptspeise",
        items: [
          "Piccata Milanese (Pute oder Kalb) auf Tomatensauce mit Butterspaghetti",
          "Schweinelende mit Kräuter-Frischkäsefüllung, Bratensauceund Zucchini-Rösti",
          "Schweinemedaillons im Speckmantel mit Tomatensauce und Kartoffelgnocchis",
          "Rinderrouladen nach Art des Hauses mit kräftiger Rotweinsauce und Kartoffelknödel",
          "Schwäbische Maultaschen mit Zwiebelschmälze und Kartoffel-Gurkensalat",
          "Ravioli mit Spinat-Ricottafüllung auf Tomaten-Basilikum-Concassée",
          "Buntes Paprikageschnetzeltes mit Schwenkkartoffeln",
          "Schaschlik auf würziger Sauce mit Gemüsereis",
          "Zarte Lammkeule Stangenbohnen im Speckmantel mit Rosmarinkartoffeln",
          "Tagliatelle verde mit Lachssahne",
          "Saltimbocca vom Lachs Blattspinat und Schwenkkartoffeln",
          "Schwäbische Kutteln in Weinsauce mit Bratkartoffeln",
          "Schwäbischer Linsenteller mit Saiten Wurst und Spätzle",
          "Zwiebelschnitzel gratiniert auf Bratensauce mit Kartoffelplätzchen",
          "Zarter Rahmsauerbraten mit Eierspätzle und Kaisergemüse",
          "Gemüsebratling mit heller Käsesauce und buntem Reis",
          "Asia-Pfanne mit Chinagemüse, Mie-Nudeln und Putenstreifen ",
          "Italienische Lasagne mit Hackfleisch oder Lachs und Spinat oder Gemüsefüllung  ",
          "Kartoffel Gratin Klassisch oder mit Hähnchen",
          "Gebratene Hähnchenbrust eingelegt in Orangensoße ",
          "Gegrillte Lachsfilet eingelegt in Honig und Petersilie ",
          "Gefüllte Paprika mit Bulgur und Feta",
          "Gefüllte Hähnchenbrust mit Gemüse und Brokkoli",
        ],
      },
    ],
  },
  {
    name: "„Die Glücklichen Ehepaar“ Buffet",
    terms: "ab 20 Personen",
    price: "48,30",
    items: [
      {
        name: "Suppe",
        items: ["Festtagssuppe"],
      },
      {
        name: "Vorspeise Und Salate",
        items: [
          "Variation aus Fluss und Meer",
          "Sahnemeerrettich, Senf-Orangensauce",
          "Gegrillte Gemüse eingelegt in nativem Olivenöl",
          "Anti pasti Spieße mit",
          "Tomate-Mozzarella, Melone-Schinken, Hirtenkäse und Oliven",
          "Halbe gefüllte Eier, individuell garniert",
          "Tomaten mit Ziegenfrischkäsefüllung",
          "Lachstatar auf gerösteter Weißbrotscheibe",
          "Festplatte „…“ mit leckeren Tunken",
          "(Truthahnröllchen verschieden gefüllt,",
          "Auswahl von Terrinen und Pasteten)",
          "Rucola mit Paprika und Champignons",
          "Toskanischer Brotsalat",
          "Bunte Blattsalate der Saison",
          "Zwei Dressings",
          "Selbstgebackenes Brot",
        ],
      },
      {
        name: "Hauptspeise",
        items: [
          "Frisch vom Grill und aus der Pfanne",
          "Medaillons vom Schweinefilet",
          "Kleine Rostbraten, Röstzwiebel",
          "Kräftige Rotweinsauce",
          "Helle Marsalasauce",
          "Claress-Fischfilet, frisch gebraten",
          "Fischsamtsauce",
          "Schwäbische Eierspätzle",
          "Kartoffel-Lauchgratin",
          "Reismosaik",
          "Variation von Gartengemüsen",
        ],
      },
      {
        name: "Nachspeise",
        items: [
          "Obstsalat mit frischen Walnüssen",
          "Geschichtete Joghurtcreme unter der Mandelhaube",
        ],
      },
    ],
  },
  {
    name: "Gourmetreise Buffet",
    terms: "ab 30 Personen",
    price: "42.60",
    buffets: [
      {
        name: "Vorspeise und Salate",
        items: [
          "Pochierte Lachsforelle, reich garniert",
          "Räucherfischvariation der Saison",
          "Sahnemeerrettich, Preiselbeersahne",
          "Delikate Fischterrine",
          "Yufkaröllchen mit Spinat-Hirtenkäsefüllung",
          "Klassische Pastetenauswahl",
          "Kirschtomaten mit Ziegenfrischkäse gefüllt",
          "Zarte Filetmedaillons mit Lebermousse",
          "Waldorfsalat mit Nüssen",
          "Geflügelsalat indisch",
          "Verschiedene Rohkost- und Blattsalate",
          "Große Brotauswahl, Butter",
        ],
      },
      {
        name: "Hauptspeise",
        items: [
          "Zanderfilet gebraten",
          "Fischsamtsauce",
          "Lammrücken „provencale“",
          "Roastbeef in der Kräuterkruste",
          "Duftreis",
          "Bircher-Benner-Kartoffeln",
          "Schwäbische Eierspätzle",
          "Bunte Gemüse der Saison",
        ],
      },
      {
        name: "Nachspeise",
        items: [
          "Internationale Käseauswahl",
          "Geschichtete Mascarponecreme mit",
          "marinierten Weichselkirschen",
          "Schokoladen-Rumcreme",
        ],
      },
    ],
  },
  {
    name: "Französisches Buffet",
    terms: "ab 20 Personen",
    price: "43.60",
    items: [
      {
        name: "Vorspeise und Salate",
        items: [
          "Gebeizter Graved Lachs, Senf-Dillsauce",
          "Crêpes gefüllt mit Lachs und Rauke",
          "Zarte Forellenfilets aus dem Heißrauch",
          "Verschiedene geräucherte Makrelenfilets",
          "Schinkenröllchen mit Spargelspitzen",
          "Gebratene Pilze in Balsamico Dressing",
          "Gurkentaler mit Käse-Kräuterrosette",
          "Entenbrust, rosa gebraten mit Orangenconfit",
          "Ananas-Apfel-Karottensalat",
          "Paprika-Maissalat",
          "Gurkensalat in Joghurt-Dilldressing",
          "Chinakohl mit Orangenspalten",
          "Tomatensalat mit roten Schalotten",
          "Frische Blattsalate der Saison",
          "Zwei Dressings",
          "Gemischter Brotkorb",
        ],
      },
      {
        name: "Hauptgang",
        items: [
          "Putensteak mit gebratenen Ananasscheiben",
          "Apfel-Currysauce",
          "Medaillons vom Schweinefilet",
          "unter der Zwiebel-Kräuterhaube",
          "kräftige Bratensauce",
          "Basmatireis",
          "Kartoffelrösti",
          "Mandelbrokkoli und Baby Möhrchen",
        ],
      },
      {
        name: "Nachspeise",
        items: [
          "Variation von heller und dunkler Mousse au Chocolat",
          "Rote Grütze mit Vanillesauce",
        ],
      },
    ],
  },
  {
    name: "Getranke",
    terms:
      "Gerne servieren wir Ihnen Ihre Wunschgetränke. Bitte sprechen Sie uns an.",
    buffets: [],
  },
];
